#!/usr/bin/env python3
"""
Example: Table-Valued Functions (TVF) Support for Column Lineage

Demonstrates how clgraph tracks column lineage through Table-Valued Functions:
- Generator TVFs (GENERATE_SERIES, GENERATE_DATE_ARRAY)
- External data TVFs (READ_CSV)
- Synthetic column marking
- TVF parameters in lineage
"""

from clgraph import JSONExporter, Pipeline, RecursiveLineageBuilder


def main():
    # Example 1: GENERATE_SERIES (PostgreSQL/DuckDB)
    print("=" * 70)
    print("Example 1: GENERATE_SERIES - Generator TVF")
    print("=" * 70)

    sql_generate_series = """
    SELECT num * 2 AS doubled
    FROM GENERATE_SERIES(1, 10) AS t(num)
    """

    builder = RecursiveLineageBuilder(sql_generate_series, dialect="postgres")
    graph = builder.build()

    print("\nSQL:")
    print(sql_generate_series)

    print("\nColumn Lineage:")
    for name, node in graph.nodes.items():
        if node.is_synthetic:
            print(f"  {name} [SYNTHETIC from {node.synthetic_source}]")
        else:
            print(f"  {name}")

    print("\nEdges:")
    for edge in graph.edges:
        tvf_marker = " [TVF output]" if edge.is_tvf_output else ""
        print(f"  {edge.from_node.full_name} -> {edge.to_node.full_name}{tvf_marker}")

    # Example 2: Multiple TVFs in JOIN
    print("\n" + "=" * 70)
    print("Example 2: Multiple TVFs with JOIN")
    print("=" * 70)

    sql_multi_tvf = """
    SELECT
        d.num AS day_num,
        h.num AS hour_num
    FROM GENERATE_SERIES(1, 31) AS d(num)
    CROSS JOIN GENERATE_SERIES(0, 23) AS h(num)
    """

    builder2 = RecursiveLineageBuilder(sql_multi_tvf, dialect="postgres")
    graph2 = builder2.build()

    print("\nSQL:")
    print(sql_multi_tvf)

    print("\nSynthetic columns from TVFs:")
    for name, node in graph2.nodes.items():
        if node.is_synthetic:
            print(f"  {name}: generated by {node.synthetic_source}")

    # Example 3: TVF in Pipeline with CREATE TABLE
    print("\n" + "=" * 70)
    print("Example 3: TVF in Pipeline")
    print("=" * 70)

    sql_pipeline = """
    CREATE TABLE date_range AS
    SELECT num AS day_number
    FROM GENERATE_SERIES(1, 365) AS t(num)
    """

    pipeline = Pipeline([("create_dates", sql_pipeline)], dialect="postgres")

    print("\nSQL:")
    print(sql_pipeline)

    print("\nPipeline columns:")
    for name, col in pipeline.column_graph.columns.items():
        synth = f" [from {col.synthetic_source}]" if col.is_synthetic else ""
        print(f"  {name}{synth}")

    print("\nPipeline edges:")
    for edge in pipeline.column_graph.edges:
        print(f"  {edge.from_node.full_name} -> {edge.to_node.full_name} [{edge.edge_type}]")

    # Example 4: JSON Export with TVF metadata
    print("\n" + "=" * 70)
    print("Example 4: JSON Export with TVF Metadata")
    print("=" * 70)

    exporter = JSONExporter()
    export_data = exporter.export(pipeline)

    import json

    print("\nExported columns with synthetic info:")
    for col in export_data.get("columns", []):
        if col.get("is_synthetic"):
            print(json.dumps(col, indent=2))

    print("\nExported edges with TVF info:")
    for edge in export_data.get("edges", []):
        if edge.get("is_tvf_output"):
            print(json.dumps(edge, indent=2))
            break

    # Example 5: READ_CSV (DuckDB) - External TVF
    print("\n" + "=" * 70)
    print("Example 5: READ_CSV - External Data TVF")
    print("=" * 70)

    sql_read_csv = """
    SELECT *
    FROM READ_CSV('s3://bucket/data.csv') AS t
    """

    from clgraph.query_parser import RecursiveQueryParser

    parser = RecursiveQueryParser(sql_read_csv, dialect="duckdb")
    unit_graph = parser.parse()

    print("\nSQL:")
    print(sql_read_csv)

    print("\nTVF sources detected:")
    for unit in unit_graph.units.values():
        for alias, tvf in unit.tvf_sources.items():
            print(f"  {alias}: {tvf.function_name} ({tvf.tvf_type.value})")
            if tvf.external_source:
                print(f"    External source: {tvf.external_source}")

    # Summary
    print("\n" + "=" * 70)
    print("Summary")
    print("=" * 70)
    print(
        """
Table-Valued Functions support captures:
- Generator TVFs (GENERATE_SERIES, GENERATE_DATE_ARRAY)
- External data TVFs (READ_CSV, READ_PARQUET)
- Column aliases from TVF AS t(col1, col2) syntax
- TVF parameters (start, end, step values)
- External source paths for file-reading TVFs

Synthetic columns are marked with:
- is_synthetic: True
- synthetic_source: function name (e.g., "generate_series")
- tvf_parameters: parameter dictionary

This metadata is preserved through:
- RecursiveLineageBuilder (single query analysis)
- Pipeline (multi-query analysis)
- JSON export
"""
    )


if __name__ == "__main__":
    main()
